WITH preset(name, rules_json) AS (
  VALUES
    ('清爽阅读', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#273444","maxWidth":677},"title":{"fontSize":31,"fontWeight":800,"lineHeight":1.32,"color":"#102a43"},"body":{"fontSize":16,"lineHeight":1.95,"paragraphSpacing":20},"heading":{"fontSize":21,"color":"#2563eb","borderColor":"#60a5fa"},"quote":{"background":"#f8fafc","borderColor":"#93c5fd"},"image":{"borderRadius":12,"spacing":22,"captionColor":"#64748b"},"divider":{"color":"#dbeafe","thickness":1},"layout":{"titleVariant":"label","headingVariant":"left-bar","imageVariant":"framed","quoteVariant":"card","dividerVariant":"dots","leadVariant":"stripe"}}'::jsonb),
    ('商务报告', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#243044","maxWidth":677},"title":{"fontSize":30,"fontWeight":800,"lineHeight":1.28,"color":"#172554"},"body":{"fontSize":16,"lineHeight":1.82,"paragraphSpacing":16},"heading":{"fontSize":20,"color":"#1e3a8a","borderColor":"#1e3a8a"},"quote":{"background":"#eff6ff","borderColor":"#3b82f6"},"image":{"borderRadius":0,"spacing":18,"captionColor":"#64748b"},"divider":{"color":"#94a3b8","thickness":2},"layout":{"titleVariant":"split","headingVariant":"numbered","imageVariant":"framed","quoteVariant":"outline","dividerVariant":"label","leadVariant":"card"}}'::jsonb),
    ('科技媒体', '{"schemaVersion":1,"canvas":{"background":"#f8fbff","textColor":"#1e293b","maxWidth":677},"title":{"fontSize":32,"fontWeight":900,"lineHeight":1.22,"color":"#0f172a"},"body":{"fontSize":16,"lineHeight":1.86,"paragraphSpacing":18},"heading":{"fontSize":21,"color":"#0369a1","borderColor":"#06b6d4"},"quote":{"background":"#ecfeff","borderColor":"#38bdf8"},"image":{"borderRadius":10,"spacing":22,"captionColor":"#475569"},"divider":{"color":"#7dd3fc","thickness":2},"layout":{"titleVariant":"poster","headingVariant":"pill","imageVariant":"shadow","quoteVariant":"bubble","dividerVariant":"dots","leadVariant":"stripe"}}'::jsonb),
    ('人文杂志', '{"schemaVersion":1,"canvas":{"background":"#fffdf8","textColor":"#3f3a34","maxWidth":677},"title":{"fontSize":31,"fontWeight":700,"lineHeight":1.42,"color":"#292524"},"body":{"fontSize":17,"lineHeight":2.05,"paragraphSpacing":22},"heading":{"fontSize":21,"color":"#9a3412","borderColor":"#c08457"},"quote":{"background":"#faf5ed","borderColor":"#d6b38a"},"image":{"borderRadius":4,"spacing":24,"captionColor":"#78716c"},"divider":{"color":"#d6b38a","thickness":1},"layout":{"titleVariant":"card","headingVariant":"stamp","imageVariant":"framed","quoteVariant":"bubble","dividerVariant":"dots","leadVariant":"kicker"}}'::jsonb),
    ('现代报刊', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#202020","maxWidth":677},"title":{"fontSize":34,"fontWeight":900,"lineHeight":1.16,"color":"#111111"},"body":{"fontSize":16,"lineHeight":1.78,"paragraphSpacing":16},"heading":{"fontSize":22,"color":"#111111","borderColor":"#111111"},"quote":{"background":"#f5f5f5","borderColor":"#4b5563"},"image":{"borderRadius":0,"spacing":18,"captionColor":"#5f6368"},"divider":{"color":"#111111","thickness":3},"layout":{"titleVariant":"bar","headingVariant":"underline","imageVariant":"cutout","quoteVariant":"outline","dividerVariant":"label","leadVariant":"stripe"}}'::jsonb),
    ('知识长文', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#263238","maxWidth":677},"title":{"fontSize":30,"fontWeight":800,"lineHeight":1.34,"color":"#102a43"},"body":{"fontSize":16,"lineHeight":1.98,"paragraphSpacing":20},"heading":{"fontSize":21,"color":"#0f766e","borderColor":"#14b8a6"},"quote":{"background":"#f0fdfa","borderColor":"#5eead4"},"image":{"borderRadius":8,"spacing":20,"captionColor":"#52606d"},"divider":{"color":"#99f6e4","thickness":1},"layout":{"titleVariant":"label","headingVariant":"band","imageVariant":"poster","quoteVariant":"card","dividerVariant":"dots","leadVariant":"card"}}'::jsonb)
)
INSERT INTO wechat_layout_system_presets (name, rules_json)
SELECT name, rules_json FROM preset
ON CONFLICT (name) DO UPDATE SET rules_json = EXCLUDED.rules_json;

WITH preset(name, rules_json) AS (
  VALUES
    ('清爽阅读', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#273444","maxWidth":677},"title":{"fontSize":31,"fontWeight":800,"lineHeight":1.32,"color":"#102a43"},"body":{"fontSize":16,"lineHeight":1.95,"paragraphSpacing":20},"heading":{"fontSize":21,"color":"#2563eb","borderColor":"#60a5fa"},"quote":{"background":"#f8fafc","borderColor":"#93c5fd"},"image":{"borderRadius":12,"spacing":22,"captionColor":"#64748b"},"divider":{"color":"#dbeafe","thickness":1},"layout":{"titleVariant":"label","headingVariant":"left-bar","imageVariant":"framed","quoteVariant":"card","dividerVariant":"dots","leadVariant":"stripe"}}'::jsonb),
    ('商务报告', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#243044","maxWidth":677},"title":{"fontSize":30,"fontWeight":800,"lineHeight":1.28,"color":"#172554"},"body":{"fontSize":16,"lineHeight":1.82,"paragraphSpacing":16},"heading":{"fontSize":20,"color":"#1e3a8a","borderColor":"#1e3a8a"},"quote":{"background":"#eff6ff","borderColor":"#3b82f6"},"image":{"borderRadius":0,"spacing":18,"captionColor":"#64748b"},"divider":{"color":"#94a3b8","thickness":2},"layout":{"titleVariant":"split","headingVariant":"numbered","imageVariant":"framed","quoteVariant":"outline","dividerVariant":"label","leadVariant":"card"}}'::jsonb),
    ('科技媒体', '{"schemaVersion":1,"canvas":{"background":"#f8fbff","textColor":"#1e293b","maxWidth":677},"title":{"fontSize":32,"fontWeight":900,"lineHeight":1.22,"color":"#0f172a"},"body":{"fontSize":16,"lineHeight":1.86,"paragraphSpacing":18},"heading":{"fontSize":21,"color":"#0369a1","borderColor":"#06b6d4"},"quote":{"background":"#ecfeff","borderColor":"#38bdf8"},"image":{"borderRadius":10,"spacing":22,"captionColor":"#475569"},"divider":{"color":"#7dd3fc","thickness":2},"layout":{"titleVariant":"poster","headingVariant":"pill","imageVariant":"shadow","quoteVariant":"bubble","dividerVariant":"dots","leadVariant":"stripe"}}'::jsonb),
    ('人文杂志', '{"schemaVersion":1,"canvas":{"background":"#fffdf8","textColor":"#3f3a34","maxWidth":677},"title":{"fontSize":31,"fontWeight":700,"lineHeight":1.42,"color":"#292524"},"body":{"fontSize":17,"lineHeight":2.05,"paragraphSpacing":22},"heading":{"fontSize":21,"color":"#9a3412","borderColor":"#c08457"},"quote":{"background":"#faf5ed","borderColor":"#d6b38a"},"image":{"borderRadius":4,"spacing":24,"captionColor":"#78716c"},"divider":{"color":"#d6b38a","thickness":1},"layout":{"titleVariant":"card","headingVariant":"stamp","imageVariant":"framed","quoteVariant":"bubble","dividerVariant":"dots","leadVariant":"kicker"}}'::jsonb),
    ('现代报刊', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#202020","maxWidth":677},"title":{"fontSize":34,"fontWeight":900,"lineHeight":1.16,"color":"#111111"},"body":{"fontSize":16,"lineHeight":1.78,"paragraphSpacing":16},"heading":{"fontSize":22,"color":"#111111","borderColor":"#111111"},"quote":{"background":"#f5f5f5","borderColor":"#4b5563"},"image":{"borderRadius":0,"spacing":18,"captionColor":"#5f6368"},"divider":{"color":"#111111","thickness":3},"layout":{"titleVariant":"bar","headingVariant":"underline","imageVariant":"cutout","quoteVariant":"outline","dividerVariant":"label","leadVariant":"stripe"}}'::jsonb),
    ('知识长文', '{"schemaVersion":1,"canvas":{"background":"#ffffff","textColor":"#263238","maxWidth":677},"title":{"fontSize":30,"fontWeight":800,"lineHeight":1.34,"color":"#102a43"},"body":{"fontSize":16,"lineHeight":1.98,"paragraphSpacing":20},"heading":{"fontSize":21,"color":"#0f766e","borderColor":"#14b8a6"},"quote":{"background":"#f0fdfa","borderColor":"#5eead4"},"image":{"borderRadius":8,"spacing":20,"captionColor":"#52606d"},"divider":{"color":"#99f6e4","thickness":1},"layout":{"titleVariant":"label","headingVariant":"band","imageVariant":"poster","quoteVariant":"card","dividerVariant":"dots","leadVariant":"card"}}'::jsonb)
),
next_versions AS (
  SELECT template.workspace_id, template.id AS template_id, preset.rules_json,
    COALESCE(max(version.version_number), 0) + 1 AS next_version
  FROM wechat_layout_templates template
  JOIN preset ON preset.name = template.name
  LEFT JOIN wechat_layout_template_versions version
    ON version.workspace_id = template.workspace_id AND version.template_id = template.id
  WHERE template.kind = 'SYSTEM'
  GROUP BY template.workspace_id, template.id, preset.rules_json
),
inserted AS (
  INSERT INTO wechat_layout_template_versions (workspace_id, template_id, version_number, rules_json, source_type)
  SELECT workspace_id, template_id, next_version, rules_json, 'SYSTEM'
  FROM next_versions
  RETURNING workspace_id, template_id, id
)
UPDATE wechat_layout_templates template
SET current_version_id = inserted.id, updated_at = now()
FROM inserted
WHERE template.workspace_id = inserted.workspace_id AND template.id = inserted.template_id;
